site_name: Sparge Documentation
site_description: Experimental JavaScript-native blockchain playground

theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy


nav:
  - Home: index.md
  - Rewards: rewards.md
  - Manifesto: manifesto.md
  - Observer Node: observer.md
  - Wallet: wallet.md
  - FAQ: faq.md
  - ops: ops.md
  - rpc: rpc.md
  - Participation: participation.md
  - Protocol Overview: protocol.md
  - Security: security.md

extra_css:
  - stylesheets/extra.css
